service: challenge-cicd-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        -  "*"
      Resource: "*"

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
